solana-foundation/stake-o-matic

.github/workflows/release.yml, fetch-release.sh
It's tedious to have to commit to making a release to get build artifacts.  Add support for `./fetch-release.sh master`
=> Add support for master binaries

Cargo.lock, Cargo.toml, patch.crates-io.sh, src/generic_stake_pool.rs, src/main.rs, src/rpc_client_utils.rs, src/stake_pool_v0.rs, update-solana-dependencies.sh
This PR adds a v0 stake pool implementation that's based on local stake split/merge operations, but conceptually behaves the  same way that the SPL Stake Pool program that @joncinque is hacking on.
There exists a reserve stake account that always will have >= 1 SOL in it.  Each validator in the pool has two stake accounts:
1. Their main stake account that is always active with >= 1 SOL in it
2. A transient stake account that is used to move stake between the reserve stake account and the validator's main account.
The single transient stake for each validator may either be activating to deactivating.  
This pool attempts to aggressively keep the reserve stake account balance at 1 SOL, so the bonus stake amount is variable based on the number of validators that are current.   The baseline …
=> Initial stake-pool v0 implementation

src/rpc_client_utils.rs, src/stake_pool_v0.rs
```
commit 0556cf8937a948993cf75c004adeb42480c2aae3 (HEAD -> ss, m/ss)
Author: Michael Vines <mvines@gmail.com>
Date:   Sat May 8 19:02:43 2021 -0700
Quiet logging
commit 5348cae467a7211aee2834be8b8c197cae579d37
Author: Michael Vines <mvines@gmail.com>
Date:   Sat May 8 18:40:19 2021 -0700
Consider transient stake when computing current balance
commit 52c36caa70f74124017a64103a6a86d1c5d83640
Author: Michael Vines <mvines@gmail.com>
Date:   Sat May 8 18:37:08 2021 -0700
Reactivate stuck validator stake
```
=> Fix some bugs

Cargo.lock, Cargo.toml, src/db.rs, src/generic_stake_pool.rs, src/main.rs
New knobs:
```
--enforce-testnet-participation    Enforce the minimum testnet participation requirement.
--min-testnet-participation <N M>...
Require that the participant's mainnet-beta validator be staked for N out of the last N epochs to be
delegable for mainnet-beta stake.
This setting is ignored if the --cluster is not `mainnet-beta`
```
Coming soon: the missing registration piece to link testnet/mainnet validators to a participant
=> Add plumbing to link testnet participation with mainnet stake

bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs
Prioritize funding smaller stake accounts to maximize the number of accounts that will be funded with the available reserve stake.
As observed on testnet, [this](https://github.com/solana-labs/stake-o-matic/wiki/Validator-4UNcH9sxWUo6bfZY93gmPiGZNssEgmG9Ho7C9ecjMv5N) validator has missed out on their baseline stake for two epochs now because some bonus nodes keep getting funded before it and the reserve stake balance is emptied.  IMO it's preferable that validators get from 0 stake to baseline stake, than validators with bonus stake receive more bonus
=> Prioritize funding smaller stake accounts

bot/src/main.rs
**Problem**
Logic for making first-in-the-epoch classifications is lumped in with whether or not to push notifications.  This prevents follower builds from pushing notifications from existing classifications.
**Solution**
Break out the booleans.
=> Enable notifications from follower builds

Cargo.lock, bot/Cargo.toml, bot/src/db.rs, bot/src/generic_stake_pool.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs
So I decided to take a different approach to modifying the stake bot for the purposes of supporting the delegation program website. This PR just adds all the data we need to the yml files. There will be a separate program that is responsible for parsing those files and updating the database.
I tested as well as I could by using the NoopStakePool; this should definitely be run in "dryrun" mode with the real stake pools a few times to test that I didn't somehow break anything.
=> Extend ValidatorClassification and EpochClassificationV1 structs to

Cargo.lock, bot/Cargo.toml, bot/src/generic_stake_pool.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, bot/src/rpc_client_utils.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs
Choose your own adventure! #163 or this.
Blockhashes expire too often while running the bot.
Use the TpuClient to send transactions instead of RpcClient.  This adapts the work from spl-token-cli to send and check transactions: https://github.com/solana-labs/solana-program-library/blob/21ae18dbd0458f9e5f18b1407a626670f6475438/token/cli/src/rpc_client_utils.rs#L36
There's a bit of churn to update parameters all over the place, but otherwise the code isn't too different.
I'll be running tests over the next couple of days to see this performs compared to the other PR, and I'll move it out of draft once the testing is complete.  If everything looks good, I'll probably opt for this.
=> bot: Use TpuClient to send transactions

bot/src/rpc_client_utils.rs, bot/src/stake_pool.rs
When confirming transactions, the new `send_and_confirm` function was just using `Processed`, while the `RpcClient` was actually at finalized.  This caused an issue when calculating how much to distribute to validators *after* creating new validator stake accounts.  When fetching the reserve stake balance, we were getting the `Finalized` balance, which was higher than the `Processed` one post-creation of new validator stake accounts.
This succeeded on the second run because we didn't create any new validator stake accounts, so the reserve balance didn't change in the middle of the run.  This means the distribution calculation was done properly the second time.
Fun fact, I found this by checking the failing transaction, and noticing that it was exactly off by 44 SOL, which seemed …
=> bot: Fix commitment used for transaction status check

bot/src/rpc_client_utils.rs
Sometimes stake-o-matic resends transactions that were eventually confirmed.  This may because the resend loop cuts out as soon as the blockhash expires.
Always check signature statuses. Side note: I like how simple this change is.
=> bot: Always check transaction statuses before resending

bot/src/stake_pool.rs
There was a failure in the stake pool job before testnet went down because the wrong minimum stake amount was used for decreasing stake.  With the update to 0.5.0, the minimum for a validator stake account went from 1 SOL + rent exemption to 0.001 SOL + rent exemption.  When decreasing, we were only checking that it was >= to the minimum (0.001 SOL), which isn't enough to split a new stake account, since that requires rent exemption.
All this to say, require that decreases be at least the rent exemption for a stake account.  Increases are OK because they can be increased by 0.001, the rent-exemption is done internally.
=> bot: Use correct minimum for stake decreases

.github/workflows/test.yml
Github actions hosted runners use three different CPU families with different instruction support.  Cached builds from one are not guaranteed to be compatible with another, resulting in SIGILL
Clear cache on CPU model change
=> ci: clear actions cache on cpu change

Cargo.lock, bot/Cargo.toml, bot/src/data_center_info.rs, bot/src/db.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, bot/src/stake_pool.rs, bot/src/validators_app.rs
Update bot to use the commission at the end of epoch
Previously, for the purposes of determining whether a validator met the max commission requirement, we used the validator's commission at the time the stake bot run. This made it so that validators could raise their commission immediately before an epoch ended, and then lower it immediately after the next epoch started, thus effectively having a high commission rate while still being in good standing with the program. This commit uses the validators.app commission-changes endpoint to determine what a validator's commission was when the epoch ended, and uses that value for determining if the validator was above the max allowed commission rate.
In addition, validators that have a commission above the max allowed for more than one epoch …
=> New commission calculation

bot/src/main.rs, stake-o-matic.sh
The participants are loaded from a hardcoded string of "https://api.mainnet-beta.solana.com", which is an issue if the endpoint is ever down.
Allow this URL to be configured on the command-line.
Note that it looks like a copy-pasta error on stake-o-matic.sh, but it's intentional -- the participant url doesn't need to be configured on mainnet since it'll just load it from the same url.
=> bot: Add participant URL parameter

bot/src/db.rs, bot/src/main.rs
Validators will now be permanently destaked if they have more than once been below max_commission at the end of one epoch, and above max_commission at the end of a subsequent epoch.
Previously we permanently destaked validators who were above max_commission for more than one epoch. This caused some validators to get permanently destaked just for failing to pay attention for a few epochs.
@t-nelson
=> Update rules for permanently destaking for high commission

bot/src/db.rs, bot/src/main.rs
Previously some validators were receiving stake even though their testnet validators were no longer running.
The cause of the problem was that we were determining if a validator had bonus or baseline in n of the last m epochs by just looking at the last m epochs found in ValidatorClassification.stake_states, but if the validator had been shut down there would be no records for those epochs, and so the validator would not be penalized.
The fix is to look in the epoch-NNN.yml files for each of the last m epochs to determine the performance of validators.
=> Fix bot to properly calculate testnet participation

rust-toolchain.toml
This should prevent unpredictable CI results caused by the CI engine
always using the latest Rust version
=> Pin Rust version to 1.60.0

stake-o-matic.sh
Currently there is a bug in how this metric is applied for mainnet.
@c3pko
=> Disable require-performance-metric-reporting for mainnet

stake-o-matic.sh
This is a temporary fix while we figure out why the bot is causing InsufficientDelegation errors to be thrown
=> bot: Increase testnet min stake

bot/src/rpc_client_utils.rs
Failed transactions only give the error, which can make it hard to learn more about the issue.
Also log the transaction signature, so we can investigate the exact error and accounts involved in an explorer.
=> bot: Log failed transaction signatures for investigation

bot/src/main.rs, bot/src/performance_db_utils.rs
If no records are found in one of the self-reporting samples, continue rather than end; only require that at least one sample has records.
Also small improvements to logged messages.
=> bot: Minor change to how self-reporting metrics are collected

bot/src/main.rs
Issues were:
- Bot was looking at the wrong testnet epochs (if MB epoch was 200, it checked TN epoch 200 instead of the current TN epoch)
- If a validator had None stake in all epochs where the bot checked for participation, the validator would not be destaked
- The most recent epoch was ignore when looking at participation
=> Bot: Fix issue with require_testnet_participation requirement

Cargo.lock, cli/Cargo.toml, cli/src/main.rs
The "list" command currently just prints the participants to stdout in no specific format (just regular formatting).
This PR adds an optional flag to allow printing all the participants in a json array. With this change, it will be much easier to parse the output. For example, suppose the output saved in a file:
```
solana-foundation-delegation-program list --state approved --output-format json > approved.json
```
Picking Python, one can then parse and operate on the elements with just a couple lines instead of regex matching
```python
import json
with open('/Users/stevecz/code/participants.json', 'r') as json_file:
data = json.load(json_file)
print(type(data))
print(type(data[0]))
for i in range(0, 5):
print(data[i])
```
And running yields:
```
<class 'list'>
<class 'dict'> …
```
=> Add an option to print list output in json format

stake-o-matic.sh
This is intended to be a temporary change. We should change back to 20 once the network improves.
=> Increase max-poor-block-produccer-percentage from 20 to 30

bot/src/rpc_client_utils.rs
The test errors are both regarding trying to create accounts that already exist, so maybe a slow connection to the test validator is causing issues. Let's try to more aggressively create the TPU client and see if that resolves it
=> Change up retry params to match a 32-slot epoch

bot/src/main.rs, bot/src/validators_app.rs
The commission-change endpoint just returned a `null` for the `commission_after` value for the first time. For now, just ignore these entries, though we should figure out what it means when this value is null.
=> Bot: Allow for null value from validators.app

bot/src/main.rs
Said "Baseline" when it should have said "Bonus"
=> Bot: Fix typo in slack message

bot/src/db.rs, bot/src/main.rs, stake-o-matic.sh
Validators with the release version or higher do not have to meet performance requirements
=> Bot: Add performance_waiver_release_version argument

bot/src/generic_stake_pool.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, bot/src/rpc_client_utils.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs, stake-o-matic.sh
stake-o-matic currently targets v1.7 solana crates. the tpu client in these crates is still the old udp one, which very few validators still have enabled and exposed to the world. this makes transaction submission very slow as transactions can only land when one of these validators is leader.
even after crates are upgraded to a newer version that supports quic tpu, not being a staked validator _may_ make tpu transaction submission unreliable as quic seats for unstaked tpu peers are limited.
since our rpc provider proxies transaction submission through staked nodes, add the ability to optionally submit transactions through them, via rpc
NOTE: #457 should land first and this branch rebased before merging
=> add ability to optionally submit transactions via rpc

bot/src/generic_stake_pool.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, bot/src/rpc_client_utils.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs
The upgrade to 1.13 is failing tests often because of reconnecting so often to a cluster with short epochs. That upgrade is very important because it uses QUIC, so it needs to be unblocked soon, especially before the cluster moves to blocking UDP totally.
Bundle the RPC and TPU clients into `Clients`, and only create the TPU client once.
Note: I also have a commit that can be added to https://github.com/solana-foundation/stake-o-matic/pull/451, but it seemed neater to *not* pile onto that PR, and instead make this change separately
Also note: I tested this by running stake-o-matic.sh with a noop stake pool on testnet
=> bot: Combine TPU and RPC clients to avoid creating TPU client

program/Cargo.toml, program/src/processor.rs
There was an issue during the upgrade to 1.13 with the program test, which would randomly give an `UnbalancedInstruction` error. See the commit messages from #465 for more info.
Avoid passing the same account twice, which doesn't work properly in 1.13, since there used to be a race when updating accounts. This is currently fixed in master, so I'll be adding a test to solana-program-test to make sure we don't introduce that regression again.
=> program: Update to Solana 1.13

bot/src/db.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, stake-o-matic.sh
If --require-dry-run-to-distribute-stake is set, the first time the bot is run in an epoch it will classify validators and save those classifications to the yml file, but it will _not_ distribute stake. The next time the bot is run in the epoch, it will load the classifications from the yml file and distribute stake.
Also add --ignore-existing-classification flag that forces re-classification of validators. Useful for test dry runs when classification has already happened.
=> bot: Save classifications before distributing stake

bot/src/main.rs, bot/src/rpc_client_utils.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs
The bot dies if it reaches a timeout on `get_program_accounts` when fetching all stake accounts. This is an extremely heavy operation, so it makes sense that it times out once in awhile.
As a first step, just wait and retry if there's a timeout.
This re-enables the stake_pool_v0 test, which was succeeding in #465, but was ignored.
=> bot: Retry `get_program_accounts` if it times out

bot/src/main.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs, stake-o-matic.sh
URLs are now set using the --mainnet-beta-json-rpc-url and --testnet-json-rpc-url flags.
=> Bot: Change how RPC URLs are set

bot/src/main.rs, bot/src/rpc_client_utils.rs, stake-o-matic.sh
If `--use-rpc-tx-submission preflight`, sends with RPC+ preflight. Any other value for `--use-rpc-tx-submission` sends with RPC and without preflight.
=> Bot: Add argument for sending transactions with RPC+Preflight

bot/src/generic_stake_pool.rs, bot/src/main.rs, bot/src/noop_stake_pool.rs, bot/src/stake_pool.rs, bot/src/stake_pool_v0.rs
This is to create more reserve SOL for subsequent epochs, so that validators are staked more quickly.
=> Reduce testnet Bonus amount by 15%
