solana-foundation/stake-o-matic

src/main.rs

more refactoring

---

.github/workflows/test.yml
src/main.rs
src/rpc_client_utils.rs

Ground work for adding epoch credits to the staking criteria...

Surface epoch_credits into main.rs

---

src/data_center_info.rs
src/main.rs

Validator data center locations are now tracked. Seniority in a DC is earned by maintaining bonus stake across epochs. When `destake-new` is active, validators with no seniority in an overpopulated DC will not be staked.

Add `--infrastructure-concentration-affects destake-new`

---

Cargo.lock
Cargo.toml
program/Cargo.toml
program/Xargo.toml
program/src/entrypoint.rs
program/src/instruction.rs
program/src/lib.rs
program/src/processor.rs
program/src/state.rs

This program will be used to manage the registration info that's currently held in a google doc.

Add registry program

---

bot/src/main.rs

Add long overdue Cluster enum

---

bot/src/main.rs

The validator in the image below was destaked for delinquency in epoch 180.  They came back strong in epoch 181 and 182, only to be dropped back to the Baseline level in epoch 183, due to how the current epoch's leader schedule is computed based on the stake from two epochs ago.  
Dropping them down to Baseline here unnecessarily punitive, both for them and the cluster.  
--------

If the validator is not in the leader schedule but was Bonus previously, maintain Bonus

---

bot/src/stake_pool.rs
bot/src/stake_pool_v0.rs

Validators at the same staking level are also now prioritized for funding based on their current stake; those with less stake are funded first

Further prioritize funding smaller stake accounts

---

stake-o-matic.sh

Move Foundation program parameters out of CI infrastructure and into the open.

Add Foundation stake bot parameters

---

bot/src/main.rs
bot/src/rpc_client_utils.rs
bot/src/stake_pool.rs
bot/src/stake_pool_v0.rs
cli/src/main.rs
program/src/processor.rs

Whenever stake-o-matic updates to nightly 2021-06-09, these lints will get tripped, so let's fix them now.

Fix clippy lints for monorepo version of nightly

---

bot/src/main.rs

#147 erroneously references `baseline_stake_amount` as global
Don't

bot: `baseline_stake_amount` is not global

---

bot/src/stake_pool.rs

Sometimes, we try to remove a validator when there are transient lamports on it, which will fail when sending out batches of transactions.
Only try to remove a validator if there's no transient stake on it.

bot: Add check to remove a validator only if there's no transient stake

---

bot/src/rpc_client_utils.rs

The mainnet job 429'ed on creation of the TpuClient, which we should be able to recover from.
Recover from any connection error on creation of the TpuClient!
Little note: I had this match in the loop originally as:
```
error @ Err(TpuSenderError::PubsubError(PubsubClientError::ConnectionError(_)))
```
which then lets us `return error;` on the last round, but it felt easier to read to just add another attempt at the end after the retries.  Happy to be overruled though!

bot: Add retry logic on TpuClient creation

---

bot/src/validator_list.rs

Remove 2ZYkM9bZeaDhxstQka6gvAGdiFYCnmxAYMwwbJKpBBm6 from validator_list

---

bot/src/main.rs

New clippy, new lint rules!
@t-nelson, @c3pko

Run `cargo clippy --fix` with clippy version 0.1.59

---

bot/src/db.rs
bot/src/main.rs
stake-o-matic.sh

This removes the generation of the markdown files, but retains the generation of the validator-summary.csv file

Remove markdown generation

---

bot/src/main.rs
bot/src/rpc_client_utils.rs

If specified RPC URL does not work, fall back to the solana.com one. 
Feature requested by @c3pko 
@t-nelson review please!

bot feature: rpc fallback

---

bot/src/rpc_client_utils.rs

Previously we counted all vote accounts when calculating the percentage of poor voters. Because there were a lot of vote accounts earning no credits, this caused there to be a high number of "poor" voters, which in turn caused the percentage of poor voters to be above config.max_poor_voter_percentage.

Don't count vote accounts with no credits when counting "poor voters"

---

bot/src/main.rs

Fix issues with dealing with missing epochs. Also fix off-by-one error in yaml files
@c3pko

Bot: Self-reporting metrics tweaks

---

bot/src/validator_list.rs

Add validator to validator_list.rs

---

bot/src/db.rs
bot/src/main.rs
stake-o-matic.sh

Enable require-perfomance-metrics-reporting

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs

Also add an unreachable!()
@c3pko

Bump CLI version to 1.0.6

---

bot/src/stake_pool_v0.rs

This is to deal with the new minimum delegation amount.
@c3pko

bot: Update minimum stake account balance

---

stake-o-matic.sh

This reverts commit a5409a388b00cdf9e512fcc399fecb57177a0f61.

Revert "bot: Increase testnet min stake"

---

bot/src/rpc_client_utils.rs

Previously changed the wrong variable (oops)
@tigarcia

bot: Increase blockhash retries

---

bot/src/rpc_client_utils.rs

bot: increase blockhash_retries to 20

---

bot/src/main.rs

This bug would would cause the bot to crash when:
- The validator reports metrics, and one of the following is true:
- The validator has been rejected, or
- The validator’s registration has been removed, or
- The testnet key for the validator’s registration has been changed.
This fix is just to ignore these validators. They are no longer in the program, so we don't need to record their self-reporting metrics

bot: Fix bug that occurred when validator registration was changed

---

bot/src/main.rs
bot/src/stake_pool_v0.rs

Also only send on the first run

Bot: Add epoch+cluster to slack message

---

bot/src/slack_utils.rs

When set, bot will send messages to Slack
When set, bot will send slack notifications

bot: Add SEND_SLACK_MESSAGES env variable

---

bot/src/main.rs

Just for testing on testnet right now

Bot: Use confirmed instead of finalized commitment level

---

fetch-release.sh

`BUILD_IT_DO_NOT_DOWNLOAD_IT` clearly hasn't been used in awhile...

fetch-release.sh: fix BUILD_IT_DO_NOT_DOWNLOAD_IT mode

---

bot/src/generic_stake_pool.rs
bot/src/main.rs
bot/src/noop_stake_pool.rs
bot/src/rpc_client_utils.rs
bot/src/stake_pool.rs
bot/src/stake_pool_v0.rs

laying ground work for other features that need to pass config values around

bot: replace websocket url with full config down to tx submit

---

bot/src/main.rs
stake-o-matic.sh

Add variables MAX_POOR_VOTER_PERCENTAGE and MIN_EPOCH_CREDIT_PERCENTAGE_OF_AVERAGE

Bot: add more env variables

---

bot/src/rpc_client_utils.rs

Don't count transactions that are in the "Processed" state as failed, and wait some time before giving up on trying to confirm a transaction. These changes seem to prevent the issue we were having of duplicate transactions getting sent and failing.
There are some performance improvements that could still be made; in particular, we could check for confirmed transactions in the loop that sends transactions, so that they could be removed and not re-sent. Also, the confirmation loop just runs ten times with a .5s pause between iterations; there is probably a smarter way of deciding when to give up.

bot: Update transaction confirmation logic

---

bot/src/stake_pool_v0.rs

This is hopefully a temporary fix.

Bot: Ignore errors collecting activation info
